### ISSUE TITLE
Does not install on macos

### ISSUE THREAD

**Issue by alexscheelmeyer** [Meteorix/pylcs#3]
It fails with a linker error:
`ld: library not found for -lstdc++`

The reason seems to be that [Xcode 10 has removed support](https://stackoverflow.com/questions/51060596/ld-library-not-found-for-lstdc-6).

**Comment by Meteorix** [comment]
@alexscheelmeyer I am using Xcode 10.2.1, and everything is right. And I have uploaded a python3.6 wheel for macos to pypi https://pypi.org/manage/project/pylcs/release/0.0.5/ . Just install the wheel, if you are using the same version.
